services:
    dynatree_solara:
        volumes:
            - ../data:/dynatree/data
            - ../outputs:/dynatree/outputs
            - ./jupyter:/dynatree/scripts/jupyter
        network_mode: bridge
        working_dir: /dynatree/scripts
        ports:
            - 8888:8888
        image: dynatree:latest
        command: ["jupyter-lab", "--allow-root", "--ip=0.0.0.0"]
        build: 
            context: ..
            dockerfile: ./docker/Dockerfile
