services:
    dynatree_solara:
        volumes:
            - ../data:/dynatree/data
            - ../outputs:/dynatree/outputs
        network_mode: bridge
        working_dir: /dynatree/scripts
        ports:
            - 8700:8700
        image: dynatree:latest
        build: 
            context: ..
            dockerfile: ./docker/Dockerfile